name: 캠핑장 예약 체크

on:
  schedule:
    # 5분마다 실행
    - cron: '*/5 * * * *'
  workflow_dispatch:  # 수동 실행을 원할 때 추가

jobs:
  camping_check:
    runs-on: ubuntu-latest  # Ubuntu 환경에서 실행

    steps:
      # 1. 리포지토리 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Python 3 설치
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # 사용하려는 Python 버전

      # 3. 의존성 설치 (requirements.txt에 있는 패키지들)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # requirements.txt에 있는 의존성 설치

      # 4. 스크립트 실행
      - name: Run camping check script
        run: |
          python test.py
