name: Python Application

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때마다 실행됩니다.
  pull_request:
    branches:
      - main  # main 브랜치에 PR을 보낼 때마다 실행됩니다.

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub에서 제공하는 Ubuntu 환경에서 실행

    steps:
    # 1. 체크아웃 - 코드를 리포지토리에서 가져옵니다.
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. 파이썬 설정 - Python 버전을 설정합니다.
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # 사용할 Python 버전을 설정합니다.

    # 3. 의존성 설치 - requirements.txt 파일에 명시된 의존성을 설치합니다.
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # requirements.txt 파일에 명시된 라이브러리들을 설치

    # 4. 파이썬 스크립트 실행 - 실제 Python 스크립트를 실행합니다.
    - name: Run Python script
      run: |
        python your_script.py  # your_script.py는 실행할 파이썬 파일 이름
